### ISSUE TITLE
Not starting on the correct level after prestiging.

### ISSUE THREAD

**Issue by AldieryGonzalez** [conorpo/conorpo.github.io#7]
I can't find where the code even is to try and solve the problem.

**Comment by AldieryGonzalez** [comment]
okay, i see only thing that may be causing the problem, but i'm not sure. On line 551, there is no code in the level variable that changes the level, but you already coded it on line 232. ( **5*pUpgrades[10]**;)

**Comment by conorpo** [comment]
Nice, fixed!
